### ISSUE TITLE
Run Gui in production mode

### ISSUE THREAD

**Issue by eeas-bekl** [ClimenteA/flaskwebgui#27]
Hi, 

i use Flask combined with waitress to be able run run flask in production mode. 

```
from flask import Flask
application= Flask(__name__)
@app.route("/")  
def index():  
  return "It works!"
```

```
from waitress import serve  
from app import application  
serve(application, host="localhost", port="5000")
```

using your ui instead of application everything crash. Is it possible to support this as well?

something like: 
```
...  
ui = FlaskUI(app)  
...  
serve(ui )
```

Best regards

**Comment by ClimenteA** [comment]
Flaskwebgui is build to make standalone desktop apps using Flask/Django other. 
Use it when you want a desktop app. 

A production environment with flaskwebgui looks like this:
- each user has python installed (or embeded python version)
- the scripts are run by linking the the main script.py file to a batch file (checkout pyvan or pyinstaller)
- if you need a commun database for the users then put an sqlite db on a sharedrive and save there the data needed

I made this setup for a 40+ team, because I didn't had resources to get some hosting + the application needed access to files on the computer/sharedrive.

**Comment by eeas-bekl** [comment]
Ok i got your point i just thought because Flaskwebgui is using development server provided by werkzeug, as written within terminal on start of the desktop app. According to flask documentation a wsgi server should be used in production mode. 

from: https://flask.palletsprojects.com/en/1.1.x/tutorial/deploy/
"
When running publicly rather than in development, you should not use the built-in development server (flask run). The development server is provided by Werkzeug for convenience, but is not designed to be particularly efficient, stable, or secure.

Instead, use a production WSGI server
"

If its not planned to be supported just close the issue. 

Still a great tool thank you!

**Comment by ClimenteA** [comment]
Glad it's useful. 
Yes flask built-in development server should not be used in production - production refers to a website that needs to handle more than one user. With flaskwebgui since needs to suport only one user you won't need something like waitress/other.
