### ISSUE TITLE
will flaskwebgui support production??

### ISSUE THREAD

**Issue by Rohith-sreedharan** [ClimenteA/flaskwebgui#88]
I tried using guicorn, but i ended up to creating infinte loop of browsers. idk why. please tell me how do i setup productions and i also want to know that like app.run('0.0.0.0', '99') is there similar to this??

**Comment by Rohith-sreedharan** [comment]
My app.py File

```
log = logging.getLogger('werkzeug')
log.setLevel(logging.WARN)

app = Flask(__name__)
app.secret_key = "secretkey"

def starts():
    ui = FlaskUI(app, width=1000, height=600, start_server="flask", port=5000)
    ui.run()

if __name__ == "__main__":
    starts()
```

the following was my command:
```
gunicorn -w 4 -b 0.0.0.0:9999 'app:saa()' 
```

excepted:
     to open one browser and run

what i get:
       i get my app, running infinte times, rather than 1.

Images:
<img width="1440" alt="Screenshot 2022-10-14 at 5 01 57 AM" src="https://user-images.githubusercontent.com/86031501/195730047-9432ffd3-5915-4090-be23-fe1e2b22a613.png">

<img width="1440" alt="Screenshot 2022-10-14 at 5 01 56 AM" src="https://user-images.githubusercontent.com/86031501/195730066-9c0f4996-60f0-4d64-a2bd-2cd56f08720b.png">

**Comment by Rohith-sreedharan** [comment]
<img width="1552" alt="Screenshot 2022-10-14 at 6 07 58 PM" src="https://user-images.githubusercontent.com/86031501/195848742-4b14d2b8-6c89-4a35-8e63-e77631434778.png">
I have specified port of 9192, instead it runs on different port that too, randomized, i am wondering why?

**Comment by ClimenteA** [comment]
Hi,

This package is to be used when you want to skip making a desktop app using any Qt* frameworks. Instead it allows you to use flask/fastapi/django etc + Chrome (chromium base browsers) to `mimic` a desktop app using the web technologies you know.  

Since a desktop app has 1 user there is no need for a production setup like you would do for a website which needs to support multiple users.

You can install waitress package (specified in docs) if you want a bit more performance in the case you have some background processes that need to run.

If the specified port is occupied then another free port will be taken. That is because as a desktop app you just need the app to start and be used.
